"""baseline：业务库六张表全量（tenants / tasks / events / tool_executions / spans / rate_windows）。

由 alembic autogenerate 从 app.storage.models.Base.metadata 生成（非手抄），
与 metadata 的一致性由 tests/test_migrations.py 的防漂移对照用例在 CI 持续把关：
改了 models 却不写新迁移，对照用例直接红。

Revision ID: 0001
Revises:
Create Date: 2026-09-21 11:07:59.276786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(length=40), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('trace_id', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index('ix_events_task_seq', ['task_id', 'seq'], unique=False)

    op.create_table('rate_windows',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scope', sa.String(length=120), nullable=False),
    sa.Column('window_start', sa.Float(), nullable=False),
    sa.Column('hits', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope', 'window_start', name='uq_rate_windows_scope_window')
    )
    op.create_table('spans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trace_id', sa.String(length=32), nullable=False),
    sa.Column('span_id', sa.String(length=16), nullable=False),
    sa.Column('parent_span_id', sa.String(length=16), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('task_id', sa.String(length=40), nullable=False),
    sa.Column('start_ts', sa.Float(), nullable=False),
    sa.Column('end_ts', sa.Float(), nullable=False),
    sa.Column('duration_ms', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attributes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('spans', schema=None) as batch_op:
        batch_op.create_index('ix_spans_trace', ['trace_id'], unique=False)

    op.create_table('tasks',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('tenant_id', sa.String(length=40), nullable=False),
    sa.Column('require_approval', sa.Boolean(), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('max_steps', sa.Integer(), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('steps_used', sa.Integer(), nullable=False),
    sa.Column('downgraded', sa.Boolean(), nullable=False),
    sa.Column('selfheal_count', sa.Integer(), nullable=False),
    sa.Column('result', sa.Text(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('duration_s', sa.Float(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_status'), ['status'], unique=False)
        batch_op.create_index('ix_tasks_tenant_created', ['tenant_id', 'created_at'], unique=False)

    op.create_table('tenants',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('api_key_hash', sa.String(length=64), nullable=False),
    sa.Column('key_prefix', sa.String(length=16), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('daily_token_quota', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenants_api_key_hash'), ['api_key_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_tenants_name'), ['name'], unique=False)

    op.create_table('tool_executions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(length=40), nullable=False),
    sa.Column('call_id', sa.String(length=80), nullable=False),
    sa.Column('tool', sa.String(length=60), nullable=False),
    sa.Column('arguments', sa.Text(), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('result', sa.Text(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('error_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'call_id', name='uq_tool_exec_task_call')
    )
    with op.batch_alter_table('tool_executions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tool_executions_task_id'), ['task_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tool_executions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tool_executions_task_id'))

    op.drop_table('tool_executions')
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenants_name'))
        batch_op.drop_index(batch_op.f('ix_tenants_api_key_hash'))

    op.drop_table('tenants')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index('ix_tasks_tenant_created')
        batch_op.drop_index(batch_op.f('ix_tasks_status'))

    op.drop_table('tasks')
    with op.batch_alter_table('spans', schema=None) as batch_op:
        batch_op.drop_index('ix_spans_trace')

    op.drop_table('spans')
    op.drop_table('rate_windows')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index('ix_events_task_seq')

    op.drop_table('events')
    # ### end Alembic commands ###
